/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author WASP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tbtn_menu_te = new javax.swing.JToggleButton();
        tbtn_menu_cafe = new javax.swing.JToggleButton();
        tbtn_menu_cervesa = new javax.swing.JToggleButton();
        tbtn_menu_soda = new javax.swing.JToggleButton();
        tbtn_menu_onigiri = new javax.swing.JToggleButton();
        tbtn_menu_burger = new javax.swing.JToggleButton();
        tbtn_menu_arroz = new javax.swing.JToggleButton();
        tbtn_menu_carne = new javax.swing.JToggleButton();
        tbtn_menu_pastel = new javax.swing.JToggleButton();
        tbtn_menu_galleta = new javax.swing.JToggleButton();
        tbtn_menu_helado = new javax.swing.JToggleButton();
        tbtn_menu_ensalada = new javax.swing.JToggleButton();
        btn_menu_cerrar = new javax.swing.JToggleButton();
        btn_menu_aceptar = new javax.swing.JToggleButton();
        cmb_menu_num = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Postres");

        jLabel3.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bebidas");

        jLabel4.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Comidas");

        tbtn_menu_te.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_te.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bebida-caliente.png"))); // NOI18N
        tbtn_menu_te.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_cafe.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_cafe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cafe.png"))); // NOI18N
        tbtn_menu_cafe.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_cervesa.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_cervesa.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerveza.png"))); // NOI18N
        tbtn_menu_cervesa.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_soda.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_soda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lata.png"))); // NOI18N
        tbtn_menu_soda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_onigiri.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_onigiri.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/onigiri.png"))); // NOI18N
        tbtn_menu_onigiri.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_burger.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_burger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/hamburguesa.png"))); // NOI18N
        tbtn_menu_burger.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_arroz.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_arroz.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/arroz.png"))); // NOI18N
        tbtn_menu_arroz.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_carne.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_carne.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/filete.png"))); // NOI18N
        tbtn_menu_carne.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_pastel.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_pastel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pastel.png"))); // NOI18N
        tbtn_menu_pastel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_galleta.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_galleta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/galletas.png"))); // NOI18N
        tbtn_menu_galleta.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_helado.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_helado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/helado.png"))); // NOI18N
        tbtn_menu_helado.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        tbtn_menu_ensalada.setBackground(new java.awt.Color(51, 51, 51));
        tbtn_menu_ensalada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ensalada.png"))); // NOI18N
        tbtn_menu_ensalada.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_menu_cerrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_menu_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btn_menu_cerrar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btn_menu_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menu_cerrarActionPerformed(evt);
            }
        });

        btn_menu_aceptar.setBackground(new java.awt.Color(51, 51, 51));
        btn_menu_aceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/comprobado.png"))); // NOI18N
        btn_menu_aceptar.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        cmb_menu_num.setBackground(new java.awt.Color(51, 51, 51));
        cmb_menu_num.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        cmb_menu_num.setForeground(new java.awt.Color(255, 255, 255));
        cmb_menu_num.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9" }));

        jLabel1.setFont(new java.awt.Font("Algerian", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Mesa:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tbtn_menu_soda)
                    .addComponent(tbtn_menu_cervesa)
                    .addComponent(tbtn_menu_cafe)
                    .addComponent(tbtn_menu_te)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_menu_cerrar)
                        .addGap(36, 36, 36)
                        .addComponent(btn_menu_aceptar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(cmb_menu_num, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtn_menu_onigiri)
                            .addComponent(tbtn_menu_burger)
                            .addComponent(tbtn_menu_arroz)
                            .addComponent(tbtn_menu_carne))
                        .addGap(149, 149, 149)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tbtn_menu_galleta, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtn_menu_helado, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtn_menu_pastel, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(tbtn_menu_ensalada, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addGap(83, 83, 83))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(59, 59, 59)
                .addComponent(jLabel2)
                .addGap(53, 53, 53))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel3)
                    .addContainerGap(383, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(tbtn_menu_te)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbtn_menu_cafe)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbtn_menu_cervesa)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tbtn_menu_soda)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btn_menu_aceptar)
                            .addComponent(btn_menu_cerrar))
                        .addGap(21, 21, 21))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbtn_menu_onigiri)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_burger)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_arroz)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_carne))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(tbtn_menu_galleta)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_helado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_pastel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tbtn_menu_ensalada)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 54, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cmb_menu_num, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(9, 9, 9))))))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(22, 22, 22)
                    .addComponent(jLabel3)
                    .addContainerGap(315, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menu_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menu_cerrarActionPerformed
        // TODO add your handling code here:
        Principal principal = new Principal();
        principal.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menu_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton btn_menu_aceptar;
    private javax.swing.JToggleButton btn_menu_cerrar;
    private javax.swing.JComboBox<String> cmb_menu_num;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToggleButton tbtn_menu_arroz;
    private javax.swing.JToggleButton tbtn_menu_burger;
    private javax.swing.JToggleButton tbtn_menu_cafe;
    private javax.swing.JToggleButton tbtn_menu_carne;
    private javax.swing.JToggleButton tbtn_menu_cervesa;
    private javax.swing.JToggleButton tbtn_menu_ensalada;
    private javax.swing.JToggleButton tbtn_menu_galleta;
    private javax.swing.JToggleButton tbtn_menu_helado;
    private javax.swing.JToggleButton tbtn_menu_onigiri;
    private javax.swing.JToggleButton tbtn_menu_pastel;
    private javax.swing.JToggleButton tbtn_menu_soda;
    private javax.swing.JToggleButton tbtn_menu_te;
    // End of variables declaration//GEN-END:variables
}
