/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Principal;

/**
 *
 * @author WASP
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btn_principal_silla1 = new javax.swing.JButton();
        btn_principal_silla2 = new javax.swing.JButton();
        btn_principal_silla3 = new javax.swing.JButton();
        btn_principal_silla4 = new javax.swing.JButton();
        btn_principal_silla5 = new javax.swing.JButton();
        btn_principal_silla6 = new javax.swing.JButton();
        btn_principal_silla7 = new javax.swing.JButton();
        btn_principal_silla8 = new javax.swing.JButton();
        btn_principal_silla9 = new javax.swing.JButton();
        btn_principal_menu = new javax.swing.JButton();
        btn_principal_cerrar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Castellar", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Restaurant");

        btn_principal_silla1.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla2.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla3.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla4.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla5.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla6.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla7.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla8.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla8.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_silla9.setBackground(new java.awt.Color(153, 153, 153));
        btn_principal_silla9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/dining-table.png"))); // NOI18N
        btn_principal_silla9.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btn_principal_menu.setBackground(new java.awt.Color(51, 51, 51));
        btn_principal_menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/menu.png"))); // NOI18N

        btn_principal_cerrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cerrar.png"))); // NOI18N
        btn_principal_cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_principal_cerrarActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/reportar.png"))); // NOI18N

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/impresora.png"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_principal_silla2)
                    .addComponent(btn_principal_silla4)
                    .addComponent(btn_principal_silla7))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_principal_silla1)
                    .addComponent(btn_principal_silla5)
                    .addComponent(btn_principal_silla8))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_principal_silla3)
                            .addComponent(btn_principal_silla6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_principal_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jButton2)))
                        .addGap(0, 44, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_principal_silla9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_principal_cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(btn_principal_silla2)
                                    .addComponent(btn_principal_silla1)
                                    .addComponent(btn_principal_silla3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_principal_silla5)
                                    .addComponent(btn_principal_silla4)
                                    .addComponent(btn_principal_silla6)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btn_principal_menu)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_principal_silla8)
                            .addComponent(btn_principal_silla7)
                            .addComponent(btn_principal_silla9)))
                    .addComponent(btn_principal_cerrar))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_principal_cerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_principal_cerrarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btn_principal_cerrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_principal_cerrar;
    private javax.swing.JButton btn_principal_menu;
    private javax.swing.JButton btn_principal_silla1;
    private javax.swing.JButton btn_principal_silla2;
    private javax.swing.JButton btn_principal_silla3;
    private javax.swing.JButton btn_principal_silla4;
    private javax.swing.JButton btn_principal_silla5;
    private javax.swing.JButton btn_principal_silla6;
    private javax.swing.JButton btn_principal_silla7;
    private javax.swing.JButton btn_principal_silla8;
    private javax.swing.JButton btn_principal_silla9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
